server:
  port: 8088
  servlet:
    context-path: /v1
# データベース接続情報の設定
spring:
  #start customize 404 error response
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  #end customize 404 error response
  datasource:
    name: mahjongdb
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/game
    username: game
    password: game    
# Actuatorを利用する際のPrefix
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
# Actuatorを利用する際のポート番号
  server:
    port: 9999
    