---
spring:
  profiles: local

  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  web:
    resources:
      static-locations: file:./src/main/resources/static/
  session:
    store-type: redis
    redis:
      namespace: mahjong
  redis:
    host: localhost
    port: 6379
websocket:
  end-point: http://localhost:8089  
  
server:
  port: 8089
application:
  uri: http://localhost:8088/v1
  path:
    home: /
    hands: /hands
    shuffled: /shuffled
    
    rooms: /room/all
    room: /room/get
    enterRoom: /room/enter
    exitRoom: /room/exit
    playersInRoom: /room/players
    createRoom: /room/new
    
    players: /player/all
    createPlayer: /player/new
    playerAuthentication: /player/authentication
    createToken: /token/new
    updateToken: /token/update
    tokenForSeries: /token/get
    removeToken: /token/delete
    invitePlayers: /player/invite
    invites4Player: /player/invites
    invited: /player/invited
    
    createGame: /game/new
    game: /game/get
    enterGame: /game/enter
    ready2GrabSeat: /game/ready2GrabSeat
    grabSeat: /game/grabSeat
    diceDealer: /game/diceDealer
    ready2Redice: /game/ready2Redice
    ready2RediceWaiting: /game/ready2RediceWaiting
    rediceDealer: /game/rediceDealer
  iss: iss
  sub: sub
  loginId: anonymous
  
  
---
spring:
  profiles: prod
    
  