server:
  port: 8089
application:
  uri: http://localhost:8088/v1
  path:
    home: /
    hands: /hands
    shuffled: /shuffled
    rooms: /room/all
    players: /player/all
    createPlayer: /player/new
    playerAuthentication: /player/authentication
spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  web:
    resources:
      static-locations: file:./src/main/resources/static/
