server:
  port: 8089
application:
  uri: http://localhost:8088/v1
  hands: /hands
spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  web:
    resources:
      static-locations: file:./src/main/resources/static/
